server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;

    location ~ /\.env {
        deny all;
    }

    location / {
        if (!-e $request_filename) {
            # 核心修改：将 /$1 换成了 ?s=/$1，完美解决死循环问题
            rewrite ^(.*)$ /index.php?s=/$1 last;
            break;
        }
    }

    # 匹配 .php 结尾的请求并交给 PHP 容器
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
    }

    client_max_body_size 100M;
}
